# Generated by Django 5.2.5 on 2025-08-31 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('homepage_url', models.URLField()),
                ('careers_url', models.URLField(blank=True, null=True)),
                ('ats', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual/Custom'), ('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('WORKDAY', 'Workday'), ('ICIMS', 'iCIMS'), ('SMARTRECRUITERS', 'SmartRecruiters'), ('TALEO', 'Taleo')], default='AUTO', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('apply_url', models.URLField()),
                ('source', models.CharField(default='auto', max_length=64)),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_snippet', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_hits', to='jobs.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'apply_url'], name='jobs_jobhit_company_63d9ab_idx'), models.Index(fields=['found_at'], name='jobs_jobhit_found_a_249483_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'apply_url'), name='uniq_company_apply_url')],
            },
        ),
    ]
