# Generated by Django 5.2.5 on 2025-09-06 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobhit',
            name='uniq_company_apply_url',
        ),
        migrations.RemoveIndex(
            model_name='jobhit',
            name='jobs_jobhit_company_63d9ab_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='active',
        ),
        migrations.AddField(
            model_name='company',
            name='data_query_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_found_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobhit',
            name='category',
            field=models.CharField(blank=True, choices=[('DS', 'Data Scientist'), ('DA', 'Data Analyst'), ('DE', 'Data Engineer'), ('INTERN', 'Data Science Intern')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobhit',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ats',
            field=models.CharField(default='AUTO', max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jobhit',
            name='apply_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobhit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='jobs.company'),
        ),
        migrations.AlterField(
            model_name='jobhit',
            name='found_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobhit',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobhit',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='jobhit',
            unique_together={('company', 'apply_url')},
        ),
        migrations.AddIndex(
            model_name='jobhit',
            index=models.Index(fields=['category'], name='jobs_jobhit_categor_1ee729_idx'),
        ),
    ]
