# Generated by Django 5.2.5 on 2025-09-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobhit_uniq_company_apply_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ats_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ats_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
